### PR TITLE
feat: add support for semantic release

### PR DESCRIPTION
**Pull request by maxisam**
Add support for semantic-release. 

In order to support semantic-release, it needs to publish from root instead of ./dist

IMHO, npm doesn't really support well on publish from sub folder. It loses the ability to insert the correct gitHead information, which stop semantic-release from working properly.

### CODE REVIEW

**Comment by robisim74** [comment]
Hey @maxisam, thanks a lot for this pr, but I can't merge it (for the moment). I explain: the goal of this project is to provide a template for _building a library compatible with Angular,_ and nothing else. It is not on npm, it has not releases: a user should be able to customize it as he pleases.

For example, I suggest to use _semantic versioning_ in the README, but if I provide a specific library as _semantic-release_, then I have to provide docs & help to use it:  in fact _semantic-release_ requires the user to work in a certain way. But it is not strategical for this project (and I could not to do tests because this project doesn't have releases).

The same considerations apply to _yarn_: after the dowloading & the updating, this template becames his library, and if the user wants, he can add it without problems.

Thanks again.

P.S. Maybe I'll add the configuration for _semantic_release_ only in the README file.

**Comment by maxisam** [comment]
It's ok. But I do think you could consider publish from root instead of dist. Is there any reason to do it this way?

**Comment by robisim74** [comment]
If you publish from root, you publish all the files in the root directory. To avoid that, you should include `"files"` in the _package.json_ but then you have to publish the whole _dist_ folder into the package: this mean that the user will have to import from:
`node_modules/my-library/dist/bundles/my-library.umd.min.js`

Instead, in this way, I publish only the _dist_ folder as root, and the package will contain only the files that I put in _dist_ folder. If you open a distribuited package of Angular, for example _@angular/common_ in _node_modules_, you will notice that it has the same structure and files, and as with an Angular package, you can use:
`node_modules/my-library/bundles/my-library.umd.min.js`

**Comment by maxisam** [comment]
actually if main field setup correctly, people who use systemjs can just reference to package@version without the whole path.

And for people who use typescript / es6, it doesn't matter to them.

With `files` field and `.npmignore`, actually we can control exactly what we want to publish. 

IMHO, the only different is folder structure. 

However, publishing from a subfolder loses the gitHead information.

I don't know why angular team does it this way tho.

Anyway, I know you were just trying to mimic the same process.

**Comment by robisim74** [comment]
I tried to recreate the building process of Angular, not the publishing process. It's a my choise. But as you said, you can change it using different settings. I think it is only important that the structure and the files of the published package is like the official package, to avoid confusion and unexpected errors to the users.

**Comment by maxisam** [comment]
Cool. Thanks for your repo anyway.

**Comment by jrgcubano** [comment]
I tried different scenarios and finally get it work using semantic-release pre and semantic-release post without changing anything of the library starter dist. Just running the build between pre and post phases. 

Example:
[travis and semantic release](https://github.com/MallorcaJS/mallorca-ng/blob/master/.travis.yml)

**Comment by robisim74** [comment]
@jrgcubano Thanks for sharing your solution. I will try it.

**Pull request closed without merging**
